services:
  studio-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studio-bot
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - studio-bot-network
    environment:
      APP_ENV: development

      RENT_ADMIN_CHAT_ID: 576077782

      RENT_CARD_NUMBER: "2204 3204 4401 8966"
      RENT_PRICE_PER_HOUR: 700
      RENT_TIMEZONE: "Europe/Moscow"

      ADMIN_PHONE: "+79214023791"
      ADMIN_USERNAME: "@amadau"

      DB_HOST: studio_postgres
      DB_PORT: 5432
      DB_USER: studio
      DB_PASSWORD: studio
      DB_NAME: studio_db
      DB_SSLMODE: disable
      DB_MAX_OPEN_CONNS: 25
      DB_MAX_IDLE_CONNS: 10
      DB_CONN_MAX_LIFETIME: 5m

      TELEGRAM_BOT_TOKEN: 8916902619:AAEa2tTOezZgh3WWZac7MmFcWks0D-hKyxk
      TELEGRAM_BOT_DEBUG: false
      TELEGRAM_BOT_TIMEOUT: 60

networks:
  studio-bot-network:
    external: true
    name: studio-bot-network

